# Generated by Django 5.1.6 on 2025-04-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_type'),
        ('business_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business_management.producttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='business_management.templatefield')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='business_management.product')),
            ],
        ),
    ]
