# Generated by Django 5.1.6 on 2025-04-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_type'),
        ('business_management', '0002_product_productfieldvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='business.business')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='business_management.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'unique_together': {('name', 'parent', 'business')},
            },
        ),
    ]
