# Generated by Django 5.1.6 on 2025-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
