# Generated by Django 5.1.6 on 2025-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0005_product_custom_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatefield',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='templatefield',
            name='currency_symbol',
            field=models.CharField(blank=True, default='$', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('currency', 'Currency'), ('dropdown', 'Dropdown'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='productfieldvalue',
            unique_together={('product', 'field')},
        ),
        migrations.DeleteModel(
            name='FieldOption',
        ),
    ]
