# Generated by Django 5.1.6 on 2025-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0006_alter_templatefield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
