# Generated by Django 5.1.6 on 2025-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateupload',
            name='field_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of form labels to field keys'),
        ),
    ]
