# Generated by Django 5.1.6 on 2025-05-03 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0010_templateupload_field_mappings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateupload',
            old_name='customer',
            new_name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='templateupload',
            unique_together={('uploaded_by', 'template_type')},
        ),
    ]
