# Generated by Django 5.1.6 on 2025-05-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0011_rename_customer_templateupload_uploaded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFieldPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Internal field key used in order data (e.g., order_id, sent_by)', max_length=100)),
                ('label', models.CharField(help_text="Display label for the field (e.g., 'Order ID')", max_length=100)),
                ('x', models.FloatField(help_text='X coordinate (in points, 72 DPI) for PDF placement')),
                ('y', models.FloatField(help_text='Y coordinate (in points, 72 DPI) for PDF placement')),
                ('page', models.PositiveIntegerField(default=1, help_text='Page number in the PDF')),
                ('font_size', models.PositiveIntegerField(default=12, help_text='Font size for rendering text')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_positions', to='business_management.templateupload')),
            ],
        ),
    ]
