# Generated by Django 5.1.6 on 2025-05-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0012_orderfieldposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateupload',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/previews/'),
        ),
    ]
