# Generated by Django 5.1.6 on 2025-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0014_order_order_number_ordernumberconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateupload',
            name='pdf_height_pt',
            field=models.FloatField(blank=True, help_text='PDF page height in points (1pt = 1/72 inch)', null=True),
        ),
        migrations.AddField(
            model_name='templateupload',
            name='pdf_width_pt',
            field=models.FloatField(blank=True, help_text='PDF page width in points (1pt = 1/72 inch)', null=True),
        ),
        migrations.AddField(
            model_name='templateupload',
            name='preview_dpi',
            field=models.PositiveIntegerField(default=150, help_text='DPI used for preview image generation'),
        ),
    ]
