# Generated by Django 5.1.6 on 2025-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0015_templateupload_pdf_height_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfieldposition',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
