# Generated by Django 5.1.6 on 2025-07-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0016_orderfieldposition_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfieldposition',
            name='height',
        ),
    ]
