# Generated by Django 5.1.6 on 2025-07-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_type'),
        ('business_management', '0017_remove_orderfieldposition_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfieldposition',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='orderfieldposition',
            name='key',
        ),
        migrations.RemoveField(
            model_name='orderfieldposition',
            name='label',
        ),
        migrations.RemoveField(
            model_name='orderfieldposition',
            name='template',
        ),
        migrations.AddField(
            model_name='orderfieldposition',
            name='field_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderfieldposition',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderfieldposition',
            name='x',
            field=models.FloatField(help_text='X coordinate in PDF points'),
        ),
        migrations.AlterField(
            model_name='orderfieldposition',
            name='y',
            field=models.FloatField(help_text='Y coordinate in PDF points'),
        ),
        migrations.CreateModel(
            name='OrderFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_form_templates', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='business_management.orderformtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='orderfieldposition',
            name='order_form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_positions', to='business_management.orderformtemplate'),
        ),
    ]
