# Generated by Django 5.1.6 on 2025-07-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0018_remove_orderfieldposition_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfieldposition',
            name='template_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_positions', to='business_management.templateupload'),
        ),
        migrations.AlterField(
            model_name='orderfieldposition',
            name='field_key',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderfieldposition',
            name='order_form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_positions', to='business_management.orderformtemplate'),
        ),
        migrations.AlterField(
            model_name='templateupload',
            name='pdf_height_pt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateupload',
            name='pdf_width_pt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateupload',
            name='preview_dpi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
