# Generated by Django 5.1.6 on 2025-07-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0019_orderfieldposition_template_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='template_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='business_management.templateupload'),
        ),
    ]
