# Generated by Django 5.1.6 on 2025-07-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0020_order_template_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='template_upload',
        ),
    ]
