# Generated by Django 5.1.6 on 2025-07-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_rejected_manufacturers'),
        ('business_management', '0021_remove_order_template_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business_management.order')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_form_templates', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFieldPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='unknown', max_length=255)),
                ('x', models.FloatField(help_text='X coordinate in PDF points')),
                ('y', models.FloatField(help_text='Y coordinate in PDF points')),
                ('page', models.IntegerField(default=1)),
                ('font_size', models.FloatField(default=11.0, help_text='Font size in points')),
                ('template_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_field_positions', to='business_management.templateupload')),
                ('invoice_form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_positions', to='business_management.invoiceformtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('textarea', 'Text Area')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='business_management.invoiceformtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='NumberConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('order', 'Order Number'), ('invoice', 'Invoice Number')], max_length=20)),
                ('start_number', models.IntegerField(default=1)),
                ('current_number', models.IntegerField(default=1)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_configs', to='business.business')),
            ],
            options={
                'verbose_name': 'Number Configuration',
                'verbose_name_plural': 'Number Configurations',
                'unique_together': {('business', 'config_type')},
            },
        ),
    ]
