# Generated by Django 5.1.6 on 2025-07-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0022_invoice_invoiceformtemplate_invoicefieldposition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderNumberConfig',
        ),
    ]
