# Generated by Django 5.1.6 on 2025-07-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0023_delete_ordernumberconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='data',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('manufacturer_to_customer', 'Manufacturer to Customer'), ('customer_to_end_customer', 'Customer to End Customer')], default='manufacturer_to_customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business_management.order'),
        ),
        migrations.AlterField(
            model_name='numberconfig',
            name='config_type',
            field=models.CharField(choices=[('order', 'Order Number'), ('manufacturer_invoice', 'Manufacturer Invoice Number'), ('customer_invoice', 'Customer Invoice Number')], max_length=20),
        ),
    ]
