# Generated by Django 5.1.6 on 2025-07-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_rejected_manufacturers'),
        ('business_management', '0025_update_existing_number_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advanced_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount already paid', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross Total - Advanced Paid', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to',
            field=models.TextField(blank=True, help_text='Customer name and address', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact_for_questions',
            field=models.CharField(blank=True, help_text='Name, phone, email for questions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Phone/email contact information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal + Sales Tax', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date of the invoice (defaults to today)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='Array of line items with quantity, description, unit_price, amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Payment instructions for customer', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.TextField(blank=True, help_text='Purchase Order number(s)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sales tax amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all line item amounts', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='thank_you_message',
            field=models.TextField(blank=True, help_text='Thank you message at bottom', null=True),
        ),
        migrations.AddField(
            model_name='invoiceformfield',
            name='calculation_formula',
            field=models.TextField(blank=True, help_text="Formula for calculated fields (e.g., 'quantity * unit_price')", null=True),
        ),
        migrations.AddField(
            model_name='invoiceformfield',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='Whether this field can be repeated (for line items)'),
        ),
        migrations.AlterField(
            model_name='invoiceformfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('textarea', 'Text Area'), ('multiline_text', 'Multi-line Text'), ('calculated', 'Calculated Field'), ('repeatable_group', 'Repeatable Group')], max_length=20),
        ),
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol (e.g., $, ₹, €)', max_length=5)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places to display')),
                ('position', models.CharField(choices=[('before', 'Before Amount'), ('after', 'After Amount')], default='before', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_configs', to='business.business')),
            ],
            options={
                'unique_together': {('business',)},
            },
        ),
    ]
