# Generated by Django 5.1.6 on 2025-07-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_rejected_manufacturers'),
        ('business_management', '0027_invoice_related_orders_alter_invoice_advanced_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='$', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('position', models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_configs', to='business.business')),
            ],
            options={
                'verbose_name': 'Currency Configuration',
                'verbose_name_plural': 'Currency Configurations',
                'unique_together': {('business', 'is_default')},
            },
        ),
    ]
