# Generated by Django 5.1.6 on 2025-01-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0028_currencyconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('pending', 'Pending'),
                    ('sent', 'Sent'),
                    ('paid', 'Paid'),
                    ('overdue', 'Overdue'),
                    ('cancelled', 'Cancelled')
                ],
                default='draft',
                max_length=20
            ),
        ),
    ] 