# Generated by Django 5.1.6 on 2025-07-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0029_add_pending_status_to_invoice'),
        ('business_management', '0029_alter_invoice_advanced_paid_alter_invoice_amount_and_more'),
    ]

    operations = [
    ]
