# Generated by Django 5.1.6 on 2025-07-31 14:52

from django.db import migrations
from decimal import Decimal, ROUND_HALF_UP


def fix_decimal_formatting(apps, schema_editor):
    """
    Fix decimal formatting for existing invoice records.
    Ensures all decimal fields have proper 2 decimal place formatting.
    """
    Invoice = apps.get_model('business_management', 'Invoice')
    
    for invoice in Invoice.objects.all():
        # Fix all decimal fields to ensure proper formatting
        invoice.subtotal = Decimal(str(invoice.subtotal)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        invoice.sales_tax = Decimal(str(invoice.sales_tax)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        invoice.gross_total = Decimal(str(invoice.gross_total)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        invoice.advanced_paid = Decimal(str(invoice.advanced_paid)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        invoice.balance_due = Decimal(str(invoice.balance_due)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        invoice.amount = Decimal(str(invoice.amount)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        invoice.save()


def reverse_fix_decimal_formatting(apps, schema_editor):
    """
    Reverse migration - no action needed as this is just data formatting.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0030_merge_20250731_1205'),
    ]

    operations = [
        migrations.RunPython(fix_decimal_formatting, reverse_fix_decimal_formatting),
    ]
