# Generated by Django 5.1.6 on 2025-08-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0031_fix_existing_decimal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
