# Generated by Django 5.1.6 on 2025-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0032_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicefieldposition',
            name='invoice_form_template',
        ),
        migrations.RemoveField(
            model_name='invoicefieldposition',
            name='template_upload',
        ),
        migrations.AlterUniqueTogether(
            name='invoiceformfield',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invoiceformfield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='invoiceformtemplate',
            name='business',
        ),
        migrations.AlterField(
            model_name='templateupload',
            name='template_type',
            field=models.CharField(choices=[('order', 'Order Form')], max_length=10),
        ),
        migrations.DeleteModel(
            name='CurrencyConfig',
        ),
        migrations.DeleteModel(
            name='InvoiceFieldPosition',
        ),
        migrations.DeleteModel(
            name='InvoiceFormField',
        ),
        migrations.DeleteModel(
            name='InvoiceFormTemplate',
        ),
    ]
