# Generated by Django 5.1.6 on 2025-08-03 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0033_remove_invoicefieldposition_invoice_form_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('manufacturer_to_customer', 'Manufacturer to Customer')], default='manufacturer_to_customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='numberconfig',
            name='config_type',
            field=models.CharField(choices=[('order', 'Order Number'), ('manufacturer_invoice', 'Manufacturer Invoice Number')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('completed', 'Completed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='business_management.order')),
            ],
            options={
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
