# Generated by Django 5.1.6 on 2025-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0034_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('order_creator', 'Order Creator'), ('dynamic_order_form', 'Dynamic Order Form')], default='order_creator', max_length=20),
        ),
    ]
