# Generated by Django 5.1.6 on 2025-08-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_rejected_manufacturers'),
        ('business_management', '0035_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateupload',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_uploads', to='business.business'),
        ),
    ]
