# Generated by Django 5.1.6 on 2025-08-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0036_templateupload_business'),
    ]

    operations = [
    ]
