# Generated by Django 5.1.6 on 2025-08-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0037_merge_20250804_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderformfield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='orderformtemplate',
            name='business',
        ),
        migrations.DeleteModel(
            name='OrderFieldPosition',
        ),
        migrations.DeleteModel(
            name='OrderFormField',
        ),
        migrations.DeleteModel(
            name='OrderFormTemplate',
        ),
    ]
