# Generated by Django 5.1.6 on 2025-08-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0038_remove_dynamic_order_form_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateUpload',
        ),
    ]
