# Generated by Django 5.1.6 on 2025-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0039_remove_template_upload_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='default_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('currency', 'Currency'), ('dropdown', 'Dropdown'), ('boolean', 'Boolean'), ('default_value', 'Default Value')], max_length=20),
        ),
    ]
