# Generated by Django 5.1.6 on 2025-08-08 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_rejected_manufacturers'),
        ('business_management', '0040_templatefield_default_value_alter_templatefield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('prediction_type', models.CharField(choices=[('sales_forecast', 'Sales Forecast'), ('product_performance', 'Product Performance'), ('trend_analysis', 'Trend Analysis')], max_length=50)),
                ('prediction_data', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('data_quality_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='business.business')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('order_count', models.IntegerField()),
                ('quantity_consistency', models.FloatField()),
                ('time_pattern_score', models.FloatField()),
                ('data_recency_score', models.FloatField()),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_confidences', to='business.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_records', to='business_management.product')),
            ],
            options={
                'unique_together': {('business', 'product')},
            },
        ),
    ]
