# Generated by Django 5.1.6 on 2025-08-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0024_performance_optimization'),
        ('business_management', '0041_alter_order_status_alter_orderstatushistory_status_and_more'),
    ]

    operations = [
    ]
