# Generated by Django 5.1.6 on 2025-08-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_rejected_manufacturers'),
        ('business_management', '0042_merge_20250809_0040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='businessmetrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='businessmetrics',
            name='business',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_business_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_due_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='numberconfig',
            name='numberconfig_business_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_business_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_customer_business_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderstatushistory',
            name='orderstatushistory_order_changed_idx',
        ),
        migrations.RemoveIndex(
            model_name='predictionrecord',
            name='predictionrecord_business_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_business_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_template_business_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_custom_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='productcategory_business_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='productconfidence',
            name='productconfidence_business_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='productfieldvalue',
            name='productfieldvalue_product_field_idx',
        ),
        migrations.RemoveIndex(
            model_name='templatefield',
            name='templatefield_template_order_idx',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='gross_total',
            new_name='tax_amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sales_tax',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer Invoice'), ('customer', 'Customer Invoice')], default='manufacturer', max_length=30),
        ),
        migrations.AlterField(
            model_name='numberconfig',
            name='config_type',
            field=models.CharField(choices=[('order', 'Order Number'), ('manufacturer_invoice', 'Manufacturer Invoice Number'), ('customer_invoice', 'Customer Invoice Number')], max_length=20),
        ),
        migrations.AddField(
            model_name='endcustomer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_customers', to='business.business'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business_management.invoice'),
        ),
        migrations.DeleteModel(
            name='BusinessMetrics',
        ),
        migrations.AlterUniqueTogether(
            name='endcustomer',
            unique_together={('name', 'business')},
        ),
    ]
