# Generated by Django 5.1.6 on 2025-08-09 18:41

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0044_auto_20250809_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add invoice_id field to InvoiceItem table
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business_management.invoice'),
        ),
        # Add business_id field to EndCustomer table
        migrations.AddField(
            model_name='endcustomer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_customers', to='business.business'),
        ),
    ]
