# Generated by Django 5.1.6 on 2025-08-11 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_contact_person_business_description_and_more'),
        ('business_management', '0045_auto_20250809_2341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('contact', 'Contact Request'), ('join', 'Join Business Request')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('manufacturer_email', models.EmailField(max_length=254)),
                ('manufacturer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer_company', models.CharField(blank=True, max_length=255, null=True)),
                ('what_manufacturing', models.TextField(help_text='What products/services do you manufacture?')),
                ('capabilities', models.TextField(help_text='Describe your manufacturing capabilities')),
                ('experience', models.TextField(help_text='Your experience and background')),
                ('message', models.TextField(help_text='Additional message to the customer')),
                ('customer_response', models.TextField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='business.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('manufacturer', 'business', 'request_type')},
            },
        ),
    ]
