# Generated by Django 5.1.6 on 2025-08-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0046_manufacturerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerrequest',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='manufacturerrequest',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='manufacturerrequest',
            name='what_manufacturing',
        ),
        migrations.AlterField(
            model_name='manufacturerrequest',
            name='message',
            field=models.TextField(help_text='Manufacturing details and message to the customer'),
        ),
    ]
