# Generated by Django 5.1.6 on 2025-08-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0048_proposal_proposalresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalresponse',
            name='price_quote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
