# Generated by Django 5.1.6 on 2025-08-13 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0050_chatroom_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
