# Generated by Django 5.1.6 on 2025-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0051_chatroom_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='deleted_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('manufacturer', 'Manufacturer')], max_length=20, null=True),
        ),
    ]
