# Generated by Django 5.1.6 on 2025-08-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0052_remove_chatroom_deleted_by_chatroom_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='deleted_by',
        ),
    ]
