# Generated by Django 5.1.6 on 2025-08-14 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0053_remove_chatroom_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'manufacturer', 'request')},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='proposal_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='business_management.proposalresponse'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='business_management.manufacturerrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'manufacturer', 'proposal_response'), ('customer', 'manufacturer', 'request')},
        ),
    ]
