# Generated by Django 5.1.6 on 2025-08-16 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_business_is_public'),
        ('business_management', '0054_alter_chatroom_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'manufacturer', 'proposal_response'), ('customer', 'manufacturer', 'request')},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='business.business'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'manufacturer', 'business'), ('customer', 'manufacturer', 'proposal_response'), ('customer', 'manufacturer', 'request')},
        ),
    ]
