# Generated by Django 5.1.6 on 2025-03-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
