# Generated by Django 5.1.6 on 2025-03-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_business_invite_code'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='business.business'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
