# Generated by Django 5.1.6 on 2025-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_user_business_delete_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
