# Generated by Django 5.1.6 on 2025-07-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_user_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
    ]
