# Generated by Django 5.1.6 on 2025-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='manufacturing_country',
        ),
        migrations.AddField(
            model_name='business',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
