# Generated by Django 5.1.6 on 2025-03-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_manufacturing_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='type',
        ),
    ]
