# Generated by Django 5.1.6 on 2025-07-19 10:05

import business.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='pending_manufacturers',
            field=models.ManyToManyField(blank=True, related_name='pending_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='invite_code',
            field=models.CharField(default=business.models.generate_invite_code, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
