# Generated by Django 5.1.6 on 2025-07-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_owner_business_pending_manufacturers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='business',
            name='pending_manufacturers',
        ),
    ]
