# Generated by Django 5.1.6 on 2025-07-28 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_manufacturer_business_pending_manufacturers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rejected_manufacturers',
            field=models.ManyToManyField(blank=True, related_name='rejected_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
