# Generated by Django 5.1.6 on 2025-08-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_contact_person_business_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='shipping_country',
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
