# Generated by Django 5.1.6 on 2025-08-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_business_shipping_country_business_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
    ]
