# Generated by Django 5.1.6 on 2025-08-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_business_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
    ]
