# Generated by Django 5.1.6 on 2025-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_remove_business_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this business is visible to manufacturers in discovery'),
        ),
    ]
